document.addEventListener('DOMContentLoaded',function(){
    var sb=document.querySelector('.sidebar'),mb=document.querySelector('.mobile-toggle');
    var ov=document.createElement('div');
    ov.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.4);z-index:999;display:none';
    document.body.appendChild(ov);
    if(mb){mb.onclick=function(){sb.classList.toggle('show');ov.style.display=sb.classList.contains('show')?'block':'none'};ov.onclick=function(){sb.classList.remove('show');ov.style.display='none'}}
    var cp=window.location.pathname;
    document.querySelectorAll('.sidebar-nav .nav-link').forEach(function(l){var h=l.getAttribute('href');if(h&&cp.startsWith(h)&&h!='/')l.classList.add('active');else if(h==='/'&&cp==='/')l.classList.add('active')});
    document.querySelectorAll('[data-cf]').forEach(function(b){b.addEventListener('click',function(e){if(!confirm('Delete this record?'))e.preventDefault()})});
    var si=document.getElementById('psi'),sr=document.getElementById('psr'),dt;
    if(si&&sr){si.addEventListener('input',function(){clearTimeout(dt);var q=this.value.trim();if(q.length<2){sr.innerHTML='';sr.style.display='none';return}dt=setTimeout(function(){fetch('/patients/api/search?q='+encodeURIComponent(q)).then(function(r){return r.json()}).then(function(d){sr.innerHTML=d.length?d.map(function(p){return'<a class="dropdown-item fs12" href="/patients/history/'+p.patient_id+'"><strong>'+esc(p.name)+'</strong> <span class="text-muted">'+esc(p.phone)+'</span></a>'}).join(''):'<div class="dropdown-item fs12 text-muted">None found</div>';sr.style.display='block'}).catch(function(){sr.style.display='none'})},300)});document.addEventListener('click',function(e){if(!si.contains(e.target)&&!sr.contains(e.target))sr.style.display='none'})}
    var ab=document.getElementById('addPr');if(ab){ab.addEventListener('click',function(){var c=document.getElementById('prRows'),opts=c.dataset.opts||'',r=document.createElement('div');r.className='presc-row';r.innerHTML='<div class="row g-2 align-items-end"><div class="col-md-3"><label class="fl">Medicine</label><select name="medicine_id[]" class="form-select fc" required><option value="">Select</option>'+opts+'</select></div><div class="col-md-1"><label class="fl">Qty</label><input type="number" name="quantity[]" class="form-control fc" min="1" value="10" required></div><div class="col-md-2"><label class="fl">Dosage</label><input type="text" name="dosage[]" class="form-control fc" placeholder="e.g. Twice daily" required></div><div class="col-md-1"><label class="fl">Days</label><input type="number" name="duration_days[]" class="form-control fc" min="1" value="7" required></div><div class="col-md-3"><label class="fl">Instructions</label><input type="text" name="instructions[]" class="form-control fc" placeholder="After food"></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger btn-sm w-100" onclick="this.closest(\'.presc-row\').remove()">Remove</button></div></div>';c.appendChild(r)})}
});
function esc(s){if(!s)return'';var d=document.createElement('div');d.appendChild(document.createTextNode(s));return d.innerHTML}
